# Generated by Django 3.2.8 on 2021-10-17 02:56

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_name', models.CharField(max_length=200)),
                ('date_creation', models.DateField()),
                ('date_abolition', models.DateField()),
                ('exist', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reorganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('ord_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorganization', to='OrgStructure.ord')),
            ],
        ),
        migrations.CreateModel(
            name='TypeReorganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reorganization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StructureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('structure_code', models.CharField(max_length=50)),
                ('date_creation', models.DateField()),
                ('date_excluding', models.DateField()),
                ('exist', models.BooleanField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('org_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_unit', to='OrgStructure.orgunit')),
                ('reason_creation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_unit_creation', to='OrgStructure.reorganization')),
                ('reason_excluding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_unit_excluding', to='OrgStructure.reorganization')),
                ('subordinating', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='OrgStructure.structureunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reorganization',
            name='type_reorganization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorganization', to='OrgStructure.typereorganization'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='reason_abolition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_unit_abolition', to='OrgStructure.reorganization'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='reason_creation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_unit_creation', to='OrgStructure.reorganization'),
        ),
    ]
