# Generated by Django 3.2.8 on 2021-10-17 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgStructure', '0002_alter_structureunit_org_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structureunit',
            old_name='subordinating',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='org_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_unit', to='OrgStructure.orgunit'),
        ),
    ]
