# Generated by Django 3.2.8 on 2021-10-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgStructure', '0003_auto_20211017_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='date_abolition',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='reason_abolition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_unit_abolition', to='OrgStructure.reorganization'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='reason_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_unit_creation', to='OrgStructure.reorganization'),
        ),
    ]
