# Generated by Django 3.2.8 on 2021-10-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgStructure', '0004_auto_20211017_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='current_short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='current_structure_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
