# Generated by Django 3.2.8 on 2021-10-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgStructure', '0005_auto_20211017_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reorganization',
            name='note',
            field=models.CharField(max_length=200),
        ),
    ]
