# Generated by Django 3.2.8 on 2021-10-21 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgStructure', '0010_auto_20211021_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgunit',
            options={'ordering': ['current_name', '-date_creation'], 'verbose_name': 'подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='current_name',
            field=models.CharField(max_length=200, verbose_name='Текущее наименование'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='current_short_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Текущая аббривеатура'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='current_structure_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текущий структурный код'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='date_abolition',
            field=models.DateField(blank=True, null=True, verbose_name='Дата упразднения'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='date_creation',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='exist',
            field=models.BooleanField(verbose_name='Подразделение существует?'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='reason_abolition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_unit_abolition', to='OrgStructure.reorganization', verbose_name='Причина упразднения'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='reason_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_unit_creation', to='OrgStructure.reorganization', verbose_name='Причина создания'),
        ),
        migrations.AlterField(
            model_name='reorganization',
            name='ord_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorganization', to='OrgStructure.ord', verbose_name='Причина реорганизации (ОРД)'),
        ),
    ]
