# Generated by Django 3.2.8 on 2021-10-23 03:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('OrgStructure', '0012_alter_orgunit_exist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structureunit',
            options={'verbose_name': 'структурную единицу', 'verbose_name_plural': 'Структура'},
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='date_creation',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата ввода в структуру'),
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='date_excluding',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исключения из структуры'),
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='Действующее?'),
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_unit', to='OrgStructure.orgunit', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='OrgStructure.structureunit', verbose_name='Подчиняется'),
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='reason_creation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_unit_creation', to='OrgStructure.reorganization', verbose_name='Причина ввода'),
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='reason_excluding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_unit_excluding', to='OrgStructure.reorganization', verbose_name='Причина исключения'),
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='structure_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Структруный код'),
        ),
    ]
