# Generated by Django 3.2.8 on 2021-11-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgStructure', '0013_auto_20211023_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='reorganization',
            name='type_of_reorganization',
            field=models.CharField(choices=[('al', 'Выделение'), ('tr', 'Преобразование'), ('jo', 'Присоединение'), ('pa', 'Разделение'), ('me', 'Слияние'), ('cr', 'Создание'), ('ab', 'Упразднение')], default='Создание', max_length=2, verbose_name='Вид реорганизации'),
            preserve_default=False,
        ),
    ]
